printf "\ec"
printf "\e(0"
printf "\e[10;5H"
printf "lqqqqqqk"
printf "\e[11;5H"
printf "x  aa  x"
printf "\e[12;5H"
printf "x a  a x"
printf "\e[13;5H"
printf "x   a  x"
printf "\e[14;5H"
printf "x a  a x"
printf "\e[15;5H"
printf "x  aa  x"
printf "\e[16;5H"
printf "mqqqqqqj"
printf "\e[26;0H"
printf "\e(B"